//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Target array type is not compatible with the type of items in the collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_ARGUMENT_INVALID_TYPED_ARRAY {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_INVALID_TYPED_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only single dimensional arrays are supported for the requested action. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_ARGUMENT_MULTI_DIMENSION_ARRAY {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_MULTI_DIMENSION_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This methos is only for Enum type value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_ARGUMENT_NON_ENUM_TYPE {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_NON_ENUM_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The lower bound of target array must be zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_ARGUMENT_NON_ZERO_LOWER_BOUND_OF_ARRAY {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_NON_ZERO_LOWER_BOUND_OF_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Non-negative number required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_ARGUMENT_OUT_OF_RANGE_NEGATIVE_NUMBER {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_OUT_OF_RANGE_NEGATIVE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination array is not long enough to copy all the items in the collection. Check array index and length. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_ARGUMENT_SHORT_LENGTH_ARRAY {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_SHORT_LENGTH_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot change {0} during a {1} event. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_INVALID_OPERATION_REENTRANCY_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_INVALID_OPERATION_REENTRANCY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutating {0} by {1} is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MESSAGE_EXCEPTION_NOT_SUPPORTED_MUTATE_BY_INTERFACE_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_NOT_SUPPORTED_MUTATE_BY_INTERFACE_FORMAT", resourceCulture);
            }
        }
    }
}
