//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echo.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echo.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; value must be not a descendant of &apos;{1}&apos; value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXCEPTION_ARGUMENT_PARENT_TO_DESCENDANT_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_PARENT_TO_DESCENDANT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; value must be different from &apos;{1}&apos; value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXCEPTION_ARGUMENT_SAME_TARGET_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_SAME_TARGET_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; value must be any registered item of the collection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXCEPTION_ARGUMENT_TARGET_UNCONTAINED_ITEM_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_ARGUMENT_TARGET_UNCONTAINED_ITEM_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Organization was modified; enumeration operation may not execute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXCEPTION_INVALID_OPERATION_KEEP_ENUMERATION_WITH_MODIFIED_ORGANIZATION {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_INVALID_OPERATION_KEEP_ENUMERATION_WITH_MODIFIED_ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mutating {0} derived from {1} is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXCEPTION_NOT_SUPPORTED_MUTATE_ITEM_COLLECTION_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_EXCEPTION_NOT_SUPPORTED_MUTATE_ITEM_COLLECTION_FORMAT", resourceCulture);
            }
        }
    }
}
